name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo "Host ec2-instance" > ~/.ssh/config
          echo "  HostName 35.77.220.181" >> ~/.ssh/config
          echo "  User ec2-user" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Clone or Pull Repository
        run: |
          ssh ec2-instance << 'EOF'
            set -e
            if [ ! -d /home/ec2-user/project-rails-react ]; then
              git clone https://github.com/kazukiikuta1/project-rails-react.git /home/ec2-user/project-rails-react
            else
              cd /home/ec2-user/project-rails-react
              git pull origin main
            fi
          EOF

      - name: Deploy with Docker
        run: |
          ssh ec2-instance << 'EOF'
            cd /home/ec2-user/project-rails-react
            docker-compose down
            docker-compose up -d --build
          EOF
